// <auto-generated />
// Copyright (c) Quinntyne Brown. All Rights Reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using EventManagementPlatform.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManagementPlatform.Infrastructure.Migrations;

[DbContext(typeof(EventManagementPlatformDbContext))]
[Migration("20241222000000_RenameZipToPostalCode")]
partial class RenameZipToPostalCode
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EventManagementPlatform.Core.Model.CustomerAggregate.Customer", b =>
            {
                b.Property<Guid>("CustomerId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("BillingCity")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("BillingCountry")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("BillingPostalCode")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("BillingState")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("BillingStreet")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("CompanyName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Industry")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("PrimaryEmail")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("PrimaryPhone")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<string>("Website")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.HasKey("CustomerId");

                b.HasIndex("CompanyName");

                b.HasIndex("PrimaryEmail");

                b.ToTable("Customers");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.EquipmentAggregate.EquipmentItem", b =>
            {
                b.Property<Guid>("EquipmentItemId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Category")
                    .HasColumnType("int");

                b.Property<int>("Condition")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal?>("CurrentValue")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("Manufacturer")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Model")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime?>("ModifiedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("PurchaseDate")
                    .HasColumnType("datetime2");

                b.Property<decimal>("PurchasePrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("SerialNumber")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("WarehouseLocation")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("EquipmentItemId");

                b.HasIndex("Category");

                b.HasIndex("Status");

                b.HasIndex("Name", "Category");

                b.ToTable("EquipmentItems");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.EventAggregate.Event", b =>
            {
                b.Property<Guid>("EventId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<DateTime>("EventDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("EventTypeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid>("VenueId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("EventId");

                b.HasIndex("CustomerId");

                b.HasIndex("EventDate");

                b.HasIndex("EventTypeId");

                b.HasIndex("VenueId");

                b.ToTable("Events");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.EventAggregate.EventType", b =>
            {
                b.Property<Guid>("EventTypeId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("EventTypeId");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("EventTypes");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.StaffAggregate.StaffMember", b =>
            {
                b.Property<Guid>("StaffMemberId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("HireDate")
                    .HasColumnType("datetime2");

                b.Property<decimal?>("HourlyRate")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime?>("ModifiedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PhotoUrl")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int>("Role")
                    .HasColumnType("int");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<DateTime?>("TerminationDate")
                    .HasColumnType("datetime2");

                b.HasKey("StaffMemberId");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("Role");

                b.HasIndex("Status");

                b.ToTable("StaffMembers");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.UserAggregate.Privilege", b =>
            {
                b.Property<Guid>("PrivilegeId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AccessRight")
                    .HasColumnType("int");

                b.Property<string>("Aggregate")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("PrivilegeId");

                b.HasIndex("RoleId");

                b.ToTable("Privileges");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.UserAggregate.Role", b =>
            {
                b.Property<Guid>("RoleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("RoleId");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Roles");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.UserAggregate.User", b =>
            {
                b.Property<Guid>("UserId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("CurrentProfileId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("DefaultProfileId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ModifiedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RefreshToken")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<byte[]>("Salt")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("UserId");

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("Users");
            });

        modelBuilder.Entity("UserRoles", b =>
            {
                b.Property<Guid>("RolesRoleId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UsersUserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("RolesRoleId", "UsersUserId");

                b.HasIndex("UsersUserId");

                b.ToTable("UserRoles");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.VenueAggregate.Venue", b =>
            {
                b.Property<Guid>("VenueId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ContactEmail")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("ContactName")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("ContactPhone")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Country")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<int>("MaxCapacity")
                    .HasColumnType("int");

                b.Property<DateTime?>("ModifiedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("PostalCode")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int?>("SeatedCapacity")
                    .HasColumnType("int");

                b.Property<int?>("StandingCapacity")
                    .HasColumnType("int");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Street")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.HasKey("VenueId");

                b.HasIndex("City");

                b.HasIndex("Name");

                b.ToTable("Venues");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.EventAggregate.Event", b =>
            {
                b.HasOne("EventManagementPlatform.Core.Model.EventAggregate.EventType", "EventType")
                    .WithMany("Events")
                    .HasForeignKey("EventTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("EventType");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.UserAggregate.Privilege", b =>
            {
                b.HasOne("EventManagementPlatform.Core.Model.UserAggregate.Role", "Role")
                    .WithMany("Privileges")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");
            });

        modelBuilder.Entity("UserRoles", b =>
            {
                b.HasOne("EventManagementPlatform.Core.Model.UserAggregate.Role", null)
                    .WithMany()
                    .HasForeignKey("RolesRoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("EventManagementPlatform.Core.Model.UserAggregate.User", null)
                    .WithMany()
                    .HasForeignKey("UsersUserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.EventAggregate.EventType", b =>
            {
                b.Navigation("Events");
            });

        modelBuilder.Entity("EventManagementPlatform.Core.Model.UserAggregate.Role", b =>
            {
                b.Navigation("Privileges");
            });
#pragma warning restore 612, 618
    }
}
